# typed: false
# frozen_string_literal: true

# This file is autogenerated. DO NOT EDIT.
class Hoop < Formula
  desc "Hoop allows acessing any infra-structure resource easily and secure."
  homepage "https://github.com/hoophq/hoop"
  version "0.0.0-nightly-22b4adf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.hoop.dev/release/0.0.0-nightly-22b4adf/hoop_0.0.0-nightly-22b4adf_Darwin_amd64.tar.gz"
      sha256 "cd1fbda6ac7250bd0ffc341dfd3a3da12ddc86ab60343ec5faa3dda52f6dbc7c"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.hoop.dev/release/0.0.0-nightly-22b4adf/hoop_0.0.0-nightly-22b4adf_Darwin_arm64.tar.gz"
      sha256 "298b377469acfdbd5c870fcc30813ff3e2f2cf403f984bcb404002eff0c3df2d"

      def install
        bin.install "hoop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.hoop.dev/release/0.0.0-nightly-22b4adf/hoop_0.0.0-nightly-22b4adf_Linux_arm64.tar.gz"
      sha256 "ebb1b599e5d893a68ef9d68d49d86f658e4b763fc1b6e81ee89c5df1ac235224"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.hoop.dev/release/0.0.0-nightly-22b4adf/hoop_0.0.0-nightly-22b4adf_Linux_amd64.tar.gz"
      sha256 "23b2550c661f95bd00ee123c443deefa4627ebc234930c59c799e79289489ec1"

      def install
        bin.install "hoop"
      end
    end
  end
end
