# typed: false
# frozen_string_literal: true

# This file is autogenerated. DO NOT EDIT.
class Hoop < Formula
  desc "Hoop allows acessing any infra-structure resource easily and secure."
  homepage "https://github.com/hoophq/hoop"
  version "0.0.0-nightly-4d53003"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.hoop.dev/release/0.0.0-nightly-4d53003/hoop_0.0.0-nightly-4d53003_Darwin_amd64.tar.gz"
      sha256 "2827f0bb9472f4388b4aa0b16d61dbd4714c96bf290e0f923dd215d3bd36796d"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.hoop.dev/release/0.0.0-nightly-4d53003/hoop_0.0.0-nightly-4d53003_Darwin_arm64.tar.gz"
      sha256 "34ff3a85dd19b41bc69956ab7c2d2db13f173feab1a7274b88ea7004857c80da"

      def install
        bin.install "hoop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.hoop.dev/release/0.0.0-nightly-4d53003/hoop_0.0.0-nightly-4d53003_Linux_arm64.tar.gz"
      sha256 "b408be35dfcb59f8675fb54a24b909bdea18b2debf09f5c69ba03374621c8ba1"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.hoop.dev/release/0.0.0-nightly-4d53003/hoop_0.0.0-nightly-4d53003_Linux_amd64.tar.gz"
      sha256 "751111f84e2b8935ecfffd7b5263d06a1eaed389f6af4e4c17c5df74208b0f33"

      def install
        bin.install "hoop"
      end
    end
  end
end
