# typed: false
# frozen_string_literal: true

# This file is autogenerated. DO NOT EDIT.
class Hoop < Formula
  desc "Hoop allows acessing any infra-structure resource easily and secure."
  homepage "https://github.com/hoophq/hoop"
  version "0.0.0-nightly-b4a872e"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.hoop.dev/release/0.0.0-nightly-b4a872e/hoop_0.0.0-nightly-b4a872e_Darwin_amd64.tar.gz"
      sha256 "d17b71099ba102e7232eeaa18a37ae49c8f300f02d8e982e9e3b477cf039ee25"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.hoop.dev/release/0.0.0-nightly-b4a872e/hoop_0.0.0-nightly-b4a872e_Darwin_arm64.tar.gz"
      sha256 "78c30fe04bc01ba711a1be28860b71773e10adb2322e4fd4efc6c00ad6fb129e"

      def install
        bin.install "hoop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.hoop.dev/release/0.0.0-nightly-b4a872e/hoop_0.0.0-nightly-b4a872e_Linux_arm64.tar.gz"
      sha256 "80a3d0bfd6d66651a491996a3bcb9b62b8d057cfdf157a7b33297971988d74c8"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.hoop.dev/release/0.0.0-nightly-b4a872e/hoop_0.0.0-nightly-b4a872e_Linux_amd64.tar.gz"
      sha256 "a60f15ce82bf7d9fcded359107a9f7b1865ebcfcaae10d300ae0e5dfae8613ef"

      def install
        bin.install "hoop"
      end
    end
  end
end
